import { start } from "./browser";
import { liveData, historyData } from "./data";
import { Stock } from "./stock";
import { CronJob } from "cron";
import { transaction } from "./transaction";
import { Wallet } from "./wallet";
import { chatBot } from "./chat";
// @ts-ignore
import config from "../config.json";

const stocks = [
  ["ACS.MC", "ACS S.A."],
  ["ADS.DE", "adidas AG"],
  ["AILA.F", "Air Liquide S.A."],
  ["AIR.DE", "Airbus Group SE"],
  ["ALV.DE", "Allianz SE"],
  ["ABEA.F", "Alphabet Inc. A"],
  ["AMS.MC", "Amadeus IT Holding S.A."],
  ["AMZ.F", "Amazon.com, Inc."],
  ["AMP.MI", "Amplifon S.p.A."],
  ["ANDR.VI", "Andritz AG"],
  ["APC.F", "Apple Inc."],
  ["MTS.MC", "ArcelorMittal"],
  ["SOBA.DE", "AT&T Inc."],
  ["ATL.MI", "Atlantia S.p.A."],
  ["NDA.DE", "Aurubis AG"],
  ["AGL.MI", "Autogrill S.p.A."],
  ["AXA.F", "AXA S.A."],
  ["BBVA.MC", "Banco Bilbao Viz. Arg. S.A. (BBVA)"],
  ["BAS.DE", "BASF SE"],
  ["BAYN.DE", "Bayer AG"],
  ["BEI.DE", "Beiersdorf AG"],
  ["BIL.DE", "BHP Group Plc"],
  ["BMW.DE", "BMW AG St., Bayerische Motoren Werke"],
  ["BNP.F", "BNP Paribas S.A."],
  ["BRE.MI", "Brembo S.p.A."],
  ["CABK.MC", "Caixabank S.A."],
  ["AFX.DE", "Carl Zeiss Meditec"],
  ["CAR.F", "Carrefour S.A."],
  ["CEC.DE", "Ceconomy St."],
  ["CIS.F", "Cisco Systems Inc."],
  ["CCC3.F", "Coca-Cola Co."],
  ["CPA.F", "Colgate-Palmolive Co."],
  ["CON.DE", "Continental AG"],
  ["1COV.DE", "Covestro AG"],
  ["DAI.DE", "Daimler AG"],
  ["BSN.F", "Danone S.A. Groupe"],
  ["DLG.MI", "De'Longhi S.p.A."],
  ["DBK.DE", "Deutsche Bank AG"],
  ["DB1.DE", "Deutsche Börse AG"],
  ["LHA.DE", "Deutsche Lufthansa AG"],
  ["DPW.DE", "Deutsche Post AG"],
  ["DTE.DE", "Deutsche Telekom AG"],
  ["DWNI.DE", "Deutsche Wohnen AG"],
  ["DIA.MI", "Diasorin"],
  ["EOAN.DE", "E.ON SE"],
  ["E2F1.F", "EDF, Electricité de France"],
  ["ENG.MC", "Enagás S.A."],
  ["ENEL.MI", "ENEL S.p.A."],
  ["GZF.DE", "Engie S.A."],
  ["ENI.MI", "ENI S.p.A."],
  ["EBS.VI", "Erste Group Bank AG"],
  ["ESL.F", "EssilorLuxottica S.A."],
  ["XONA.F", "Exxon Mobil Corp."],
  ["FB2A.F", "Facebook Inc."],
  ["RACE.MI", "Ferrari N.V."],
  ["FCA.MI", "Fiat Chrysler Automobiles"],
  ["FIE.DE", "Fielmann AG"],
  ["FRA.DE", "Fraport AG"],
  ["FRE.DE", "Fresenius Medical Care AG & Co. KGaA (FMC) St."],
  ["GEC.F", "General Electric (GE) Co."],
  ["G.MI", "Generali S.p.A. Assicurazioni"],
  ["GS7.DE", "GlaxoSmithKline Plc"],
  ["HHFA.DE", "Hamburger Hafen und Logistik AG"],
  ["HNR1.DE", "Hannover Rück SE"],
  ["HEI.DE", "HeidelbergCement AG"],
  ["HLE.DE", "Hella KGaA Hueck & Co."],
  ["HFG.DE", "HelloFresh"],
  ["HEN3.DE", "Henkel KGaA Vz."],
  ["HOT.DE", "Hochtief"],
  ["7HP.F", "HP Inc."],
  ["BOSS.DE", "HUGO BOSS AG"],
  ["IMA.MI", "I.M.A. S.p.A."],
  ["IBE.MC", "Iberdrola S.A."],
  ["IBM.F", "IBM Corp."],
  ["IFX.DE", "Infineon Technologies AG"],
  ["INL.F", "Intel Corp."],
  ["ISP.MI", "Intesa Sanpaolo S.p.A."],
  ["JEN.DE", "Jenoptik"],
  ["SDF.DE", "K+S AG"],
  ["PPX.F", "Kering"],
  ["KGX.DE", "Kion Group AG"],
  ["PHI1.F", "Koninklijke Philips Electronics. N.V."],
  ["KHNZ.F", "Kraft Heinz Co."],
  ["LOR.F", "L'Oréal S.A."],
  ["LXS.DE", "LANXESS AG"],
  ["LRC.F", "LEGRAND SA Act. Prov. OPO"],
  ["LIN.DE", "Linde AG"],
  ["MOH.DE", "LVMH Moët Henn. - L. Vuitton SE"],
  ["MAN.DE", "MAN SE"],
  ["MDO.F", "McDonald's Corp."],
  ["MS.MI", "Mediaset S.p.A."],
  ["MRK.DE", "Merck KGaA"],
  ["MCH.F", "Michelin SCA"],
  ["MSF.F", "Microsoft Corp."],
  ["MLP.DE", "MLP AG"],
  ["MONC.MI", "Moncler S.p.A."],
  ["MOR.DE", "MorphoSys AG"],
  ["MTX.DE", "MTU Aero Engines AG"],
  ["MUV2.DE", "Münchener Rückversicherungs-Ge sellschaft AG"],
  ["NBP.F", "Natixis S.A."],
  ["NFC.F", "Netflix Inc."],
  ["NEXI.MI", "Nexi S.A."],
  ["NKE.F", "Nike Inc."],
  ["NOA3.F", "Nokia Oyj (Nokia Corp.)"],
  ["NDX1.DE", "Nordex AG"],
  ["OMV.VI", "OMV AG"],
  ["FTE.F", "Orange S.A."],
  ["OSR.DE", "OSRAM Licht AG"],
  ["MAT1.F", "Panasonic Corp."],
  ["PER.F", "Pernod Ricard S.A."],
  ["PFE.F", "Pfizer Inc."],
  ["PIRC.MI", "Pirelli & C"],
  ["PAH3.DE", "Porsche Automobil Holding SE Vz."],
  ["PRG.F", "Procter & Gamble Co."],
  ["PSM.DE", "ProSiebenSat.1 Media SE"],
  ["PUM.DE", "Puma SE"],
  ["RNL.F", "Renault S.A."],
  ["REY.MI", "Reply S.p.A."],
  ["REP.MC", "Repsol YPF"],
  ["RIO1.DE", "Rio Tinto Plc"],
  ["R6C.DE", "Royal Dutch Shell (A)"],
  ["RWE.DE", "RWE AG St."],
  ["GOB.DE", "Saint Gobain S.A., Compagnie de"],
  ["SZG.DE", "Salzgitter AG"],
  ["SNW.F", "Sanofi S.A."],
  ["SAP.DE", "SAP AG"],
  ["SND.DE", "Schneider Electric SE"],
  ["SES.F", "SES S.A."],
  ["SIE.DE", "Siemens AG"],
  ["SHL.DE", "Siemens Healthineers AG"],
  ["SIX2.DE", "Sixt SE"],
  ["SRG.MI", "SNAM S.p.A."],
  ["1SI.F", "Snap Inc."],
  ["SOW.DE", "Software AG"],
  ["SAX.DE", "Ströer SE"],
  ["SY1.DE", "Symrise AG"],
  ["SZU.DE", "Südzucker AG"],
  ["TMV.DE", "TeamViewer AG"],
  ["TEF.MC", "Telefónica S.A."],
  ["TL0.F", "Tesla Motors Inc."],
  ["TKA.DE", "thyssenkrupp AG"],
  ["TOTB.F", "TOTAL S.A."],
  ["TOM.F", "Toyota Motor Corp."],
  ["TUI1.DE", "TUI AG"],
  ["UEN.F", "Ubisoft Entertainment S.A."],
  ["UCG.MI", "UniCredit S.p.A."],
  ["UNVB.F", "Unilever N.V."],
  ["UN01.DE", "Uniper SE"],
  ["UTDI.DE", "United Internet AG"],
  ["VVD.DE", "Veolia Environnement S.A."],
  ["SQU.DE", "Vinci S.A."],
  ["VVU.F", "Vivendi S.A."],
  ["VODI.DE", "Vodafone Group Plc"],
  ["VOE.VI", "voestalpine AG"],
  ["VNA.DE", "Vonovia SE"],
  ["VOW3.DE", "VW AG Vz., Volkswagen"],
  ["WCH.DE", "WACKER CHEMIE AG"],
  ["WDP.F", "Walt Disney Co."],
  ["WIE.VI", "Wienerberger AG"],
  ["ZAL.DE", "Zalando SE"],
].map(([symbol, name]) => new Stock(symbol, name));

const wallet = new Wallet(50000, stocks); // 50k

async function live() {
  await start(config.website.username, config.website.password, wallet);
  liveData(stocks);
  new CronJob("* * * * *", () => transaction(wallet), null, true);
}

async function history() {
  await historyData(wallet);
  await wallet.sell(...stocks);
  console.log(wallet.money);
}

async function chat() {
  if (config.matrix !== undefined) {
    await chatBot(
      config.matrix.userId,
      config.matrix.accessToken,
      config.matrix.server,
      wallet
    );
  }
}

live();
// history();

chat();
